FROM ghcr.io/somleng/switch-app
COPY call_controller_patch.rb /app/app/call_controllers/call_controller.rb
COPY dial_string_patch.rb /app/app/models/dial_string.rb
COPY gateway_manager_patch.rb /app/app/web/gateway_manager.rb
COPY dial_verb_patch.rb /app/app/models/twiml/dial_verb.rb
COPY execute_dial_patch.rb /app/app/workflows/execute_dial.rb
